services:
  - type: web
    name: pdf-watermark-remover
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn remove_watermark_app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
